name: .NET

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '3.1.x'
    - name: Dotnet Publish
      run: dotnet publish ClimbingBot.Host -c Release -o deploy
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: '/home/runner/work/ClimbingBot/ClimbingBot/deploy/appsettings.json'
      env:
        DbConnectionString: ${{ secrets.DB_CONNTECTION_STRING }}
        Telegram.ApiKey: ${{ secrets.TELEGRAM_API_KEY }}
        Telegram.LogChatId: ${{ secrets.TELEGRAM_LOGCHAT_ID }}
        Serilog.File.Path: ${{ secrets.LOG_PATH }}
        
    - name: Copy via ssh
      uses: garygrossgarten/github-action-scp@v0.5.3
      with:
        local: /home/runner/work/ClimbingBot/ClimbingBot/deploy/
        remote: ${{ secrets.REMOTE_TARGET }}
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}
    - name: Run SSH command
      uses: garygrossgarten/github-action-ssh@v0.3.0
      with:
        command: sudo service climbingbot restart
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}
